# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1152, 864)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView_QuiverCanvas = PlotWidget(self.centralwidget)
        self.graphicsView_QuiverCanvas.setGeometry(QtCore.QRect(10, 30, 700, 700))
        self.graphicsView_QuiverCanvas.setObjectName("graphicsView_QuiverCanvas")
        self.pushButton_DeleteQuiver = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DeleteQuiver.setGeometry(QtCore.QRect(580, 740, 130, 32))
        self.pushButton_DeleteQuiver.setObjectName("pushButton_DeleteQuiver")
        self.radioButton_DrawQuiver = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_DrawQuiver.setGeometry(QtCore.QRect(720, 40, 410, 20))
        self.radioButton_DrawQuiver.setChecked(True)
        self.radioButton_DrawQuiver.setObjectName("radioButton_DrawQuiver")
        self.buttonGroup_radioButtons_drawQuiver_recordPathsAndRels = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_radioButtons_drawQuiver_recordPathsAndRels.setObjectName("buttonGroup_radioButtons_drawQuiver_recordPathsAndRels")
        self.buttonGroup_radioButtons_drawQuiver_recordPathsAndRels.addButton(self.radioButton_DrawQuiver)
        self.textBrowser_HowDoYouWritePaths = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_HowDoYouWritePaths.setGeometry(QtCore.QRect(90, 110, 540, 151))
        self.textBrowser_HowDoYouWritePaths.setWhatsThis("")
        self.textBrowser_HowDoYouWritePaths.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textBrowser_HowDoYouWritePaths.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textBrowser_HowDoYouWritePaths.setObjectName("textBrowser_HowDoYouWritePaths")
        self.pushButton_PathsLeftToRight = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PathsLeftToRight.setGeometry(QtCore.QRect(170, 200, 180, 41))
        self.pushButton_PathsLeftToRight.setWhatsThis("")
        self.pushButton_PathsLeftToRight.setObjectName("pushButton_PathsLeftToRight")
        self.pushButton_PathsRightToLeft = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PathsRightToLeft.setGeometry(QtCore.QRect(370, 200, 180, 41))
        self.pushButton_PathsRightToLeft.setObjectName("pushButton_PathsRightToLeft")
        self.listWidget_RecordedPaths = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_RecordedPaths.setGeometry(QtCore.QRect(720, 130, 410, 180))
        self.listWidget_RecordedPaths.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listWidget_RecordedPaths.setAlternatingRowColors(True)
        self.listWidget_RecordedPaths.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_RecordedPaths.setObjectName("listWidget_RecordedPaths")
        self.pushButton_AddPathToFormRelation = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AddPathToFormRelation.setGeometry(QtCore.QRect(720, 320, 130, 32))
        self.pushButton_AddPathToFormRelation.setObjectName("pushButton_AddPathToFormRelation")
        self.radioButton_RecordPathsAndRelations = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_RecordPathsAndRelations.setGeometry(QtCore.QRect(720, 70, 410, 20))
        self.radioButton_RecordPathsAndRelations.setObjectName("radioButton_RecordPathsAndRelations")
        self.buttonGroup_radioButtons_drawQuiver_recordPathsAndRels.addButton(self.radioButton_RecordPathsAndRelations)
        self.label_RecordedPaths = QtWidgets.QLabel(self.centralwidget)
        self.label_RecordedPaths.setGeometry(QtCore.QRect(720, 110, 410, 16))
        self.label_RecordedPaths.setObjectName("label_RecordedPaths")
        self.pushButton_deleteSelectedRecordedPaths = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deleteSelectedRecordedPaths.setGeometry(QtCore.QRect(860, 320, 130, 32))
        self.pushButton_deleteSelectedRecordedPaths.setObjectName("pushButton_deleteSelectedRecordedPaths")
        self.pushButton_deleteAllSelectedPaths = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deleteAllSelectedPaths.setGeometry(QtCore.QRect(1000, 320, 130, 32))
        self.pushButton_deleteAllSelectedPaths.setObjectName("pushButton_deleteAllSelectedPaths")
        self.pushButton_deleteSelectedRowInRelationBeingFormed = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deleteSelectedRowInRelationBeingFormed.setGeometry(QtCore.QRect(860, 570, 130, 32))
        self.pushButton_deleteSelectedRowInRelationBeingFormed.setObjectName("pushButton_deleteSelectedRowInRelationBeingFormed")
        self.pushButton_deleteAllRowsFromRelationBeingFormed = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deleteAllRowsFromRelationBeingFormed.setGeometry(QtCore.QRect(1000, 570, 130, 32))
        self.pushButton_deleteAllRowsFromRelationBeingFormed.setObjectName("pushButton_deleteAllRowsFromRelationBeingFormed")
        self.pushButton_formRelation = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_formRelation.setGeometry(QtCore.QRect(720, 570, 130, 32))
        self.pushButton_formRelation.setObjectName("pushButton_formRelation")
        self.pushButton_DeleteSelectedArrowsOrVertices = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DeleteSelectedArrowsOrVertices.setGeometry(QtCore.QRect(440, 740, 130, 32))
        self.pushButton_DeleteSelectedArrowsOrVertices.setObjectName("pushButton_DeleteSelectedArrowsOrVertices")
        self.tableWidget_coeffsAndPathsForRel = TableWidget(self.centralwidget)
        self.tableWidget_coeffsAndPathsForRel.setGeometry(QtCore.QRect(720, 360, 410, 200))
        self.tableWidget_coeffsAndPathsForRel.setRowCount(0)
        self.tableWidget_coeffsAndPathsForRel.setColumnCount(2)
        self.tableWidget_coeffsAndPathsForRel.setObjectName("tableWidget_coeffsAndPathsForRel")
        self.listWidget_Relations = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_Relations.setGeometry(QtCore.QRect(720, 640, 410, 171))
        self.listWidget_Relations.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listWidget_Relations.setAlternatingRowColors(True)
        self.listWidget_Relations.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_Relations.setObjectName("listWidget_Relations")
        self.label_Relations = QtWidgets.QLabel(self.centralwidget)
        self.label_Relations.setGeometry(QtCore.QRect(720, 620, 410, 16))
        self.label_Relations.setObjectName("label_Relations")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1152, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_Quiver = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_Quiver.setObjectName("dockWidget_Quiver")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dockWidget_Quiver.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_Quiver)
        self.dockWidget_PathsAndRelations = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_PathsAndRelations.setObjectName("dockWidget_PathsAndRelations")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.textEdit = QtWidgets.QTextEdit(self.dockWidgetContents_2)
        self.textEdit.setGeometry(QtCore.QRect(50, 50, 104, 85))
        self.textEdit.setObjectName("textEdit")
        self.dockWidget_PathsAndRelations.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_PathsAndRelations)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuiver = QtWidgets.QAction(MainWindow)
        self.actionQuiver.setCheckable(True)
        self.actionQuiver.setObjectName("actionQuiver")
        self.actionPaths_and_relations = QtWidgets.QAction(MainWindow)
        self.actionPaths_and_relations.setCheckable(True)
        self.actionPaths_and_relations.setObjectName("actionPaths_and_relations")
        self.actionReduction_system = QtWidgets.QAction(MainWindow)
        self.actionReduction_system.setCheckable(True)
        self.actionReduction_system.setObjectName("actionReduction_system")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuView.addAction(self.actionQuiver)
        self.menuView.addAction(self.actionPaths_and_relations)
        self.menuView.addAction(self.actionReduction_system)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_PathsLeftToRight.clicked.connect(self.pushButton_PathsLeftToRight.close)
        self.pushButton_PathsLeftToRight.clicked.connect(self.pushButton_PathsRightToLeft.close)
        self.pushButton_PathsRightToLeft.clicked.connect(self.pushButton_PathsLeftToRight.close)
        self.pushButton_PathsRightToLeft.clicked.connect(self.pushButton_PathsRightToLeft.close)
        self.pushButton_PathsRightToLeft.clicked.connect(self.textBrowser_HowDoYouWritePaths.close)
        self.pushButton_PathsLeftToRight.clicked.connect(self.textBrowser_HowDoYouWritePaths.close)
        self.pushButton_deleteAllSelectedPaths.clicked.connect(self.listWidget_RecordedPaths.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QUIVERed"))
        self.pushButton_DeleteQuiver.setText(_translate("MainWindow", "Delete quiver"))
        self.radioButton_DrawQuiver.setText(_translate("MainWindow", "Draw quiver"))
        self.textBrowser_HowDoYouWritePaths.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:24pt;\">How do you write paths?</span></p></body></html>"))
        self.pushButton_PathsLeftToRight.setText(_translate("MainWindow", "From left to right"))
        self.pushButton_PathsRightToLeft.setText(_translate("MainWindow", "From right to left"))
        self.pushButton_AddPathToFormRelation.setText(_translate("MainWindow", "Pass down sel"))
        self.radioButton_RecordPathsAndRelations.setText(_translate("MainWindow", "Record paths and relations"))
        self.label_RecordedPaths.setText(_translate("MainWindow", "Recorded paths"))
        self.pushButton_deleteSelectedRecordedPaths.setText(_translate("MainWindow", "Del sel rows"))
        self.pushButton_deleteAllSelectedPaths.setText(_translate("MainWindow", "Delete all"))
        self.pushButton_deleteSelectedRowInRelationBeingFormed.setText(_translate("MainWindow", "Del sel rows"))
        self.pushButton_deleteAllRowsFromRelationBeingFormed.setText(_translate("MainWindow", "Delete all"))
        self.pushButton_formRelation.setText(_translate("MainWindow", "Form relation"))
        self.pushButton_DeleteSelectedArrowsOrVertices.setText(_translate("MainWindow", "Delete sel"))
        self.label_Relations.setText(_translate("MainWindow", "Relations"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.dockWidget_Quiver.setWindowTitle(_translate("MainWindow", "Quiver"))
        self.dockWidget_PathsAndRelations.setWindowTitle(_translate("MainWindow", "Paths and relations"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionQuiver.setText(_translate("MainWindow", "Quiver"))
        self.actionPaths_and_relations.setText(_translate("MainWindow", "Paths and relations"))
        self.actionReduction_system.setText(_translate("MainWindow", "Reduction system"))

from pyqtgraph import PlotWidget, TableWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

